[package]
name = "dioxus-motion"
description = "Animations library for Dioxus."
version = "0.1.4"
edition = "2021"
license = "MIT"
authors = ["Sabin Regmi <get2sabin@gmail.com>"]
readme = "./README.md"
homepage = "https://wheregmis.github.io"
repository = "https://github.com/wheregmis/dioxus-motion.git"
keywords = ["dioxus", "animations"]
categories = ["graphics", "gui"]

[dependencies]
easer = "0.3.0"
dioxus-hooks = "0.6.1"
futures-util = { version = "0.3.31", default-features = false }
dioxus-signals = "0.6.1"
instant = { version = "0.1.13", optional = true }
wasm-bindgen = { version = "0.2.99", optional = true, default-features = false }
web-sys = { version = "0.3.76", optional = true, default-features = false, features = ["Window"] }
futures-channel = { version = "0.3.31", default-features = false }
# For desktop platforms
tokio = { version = "1.42.0", optional = true }


[features]
default = ["web"]
web = ["wasm-bindgen", "web-sys", "instant/wasm-bindgen"]
desktop = ["tokio", "instant"]

[dev-dependencies]
dioxus = { version = "0.6.1", default-features = false }
futures = { version = "0.3.31", default-features = false }
tokio = "1.42.0"


[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[workspace]
members = [".", "example_projects"]
